### ISSUE TITLE
Add mood check to form

### ISSUE THREAD

**Issue by ckskr** [ckskr/capstone-project#11]

**Comment by ckskr** [comment]
# Value Proposition

**As a** user
**I want to** have the possibility to insert my current mood into my diary 
**So that** I can see how I felt on a specific day 

# Description



![Image](https://user-images.githubusercontent.com/102232516/186916874-4c0a0de8-5e88-4c2c-8fab-54b67ffd2a9f.png)



# Acceptance Criteria

- [ ] List of radio buttons is shown
- [ ] on "add entry" the answered text is rendered to the diary entry
- [ ] giving an answer is required

# Tasks

(for developers team)

- [ ] Create new branch
- [ ] Add radio buttons with functionality to form
- [ ] Check how to do that best in next.js
- [ ] On button click (add entry) the answer will be rendered with the gratitude to the card (via useStore)

# Complexity

M

**Comment by RobertBReich** [comment]
Hi Claudia,

looks good to me 👍

cheers
R.
