### ISSUE TITLE
Add Styling

### ISSUE THREAD

**Issue by ckskr** [ckskr/capstone-project#12]

**Comment by ckskr** [comment]
# Value Proposition

**As a** user
**I want to** have a appealing design
**So that** I want to use the app over and over again






# Acceptance Criteria

- [ ] Add style in home screen and diary section: https://www.figma.com/file/1SucTz2r3f3FHujbN3xPU4/Daimoo?node-id=16%3A2

# Tasks

(for developers team)

- [ ] Create new branch
- [ ] Add design to each screen
- [ ] Check if links still work 
- [ ] Check if iPhone SE compatibility is given

# Complexity

M
