### ISSUE TITLE
Add daily to-dos to diary

### ISSUE THREAD

**Issue by ckskr** [ckskr/capstone-project#13]

**Comment by ckskr** [comment]
# Value Proposition

**As a** user
**I want to** have the possibility to insert the things I did on this day
**So that** I can see it in the retrospective in my diary entries

# Description





![Image](https://user-images.githubusercontent.com/102232516/187464567-6da85a77-c9f3-407f-82f6-fe149a8f886f.png)



# Acceptance Criteria

- [ ] An open input field is shown where the user can insert his daily activity
- [ ] Activity is also shown in the diary entry

# Tasks

(for developers team)

- [ ] Create new branch
- [ ] Add input field (not required)
- [ ] Add a headline to describe what the user should do
- [ ] On button click (add entry) the answer will be rendered with the other input to the card (via useStore)

# Complexity

S
