### ISSUE TITLE
#7 Add time stamp to diary entries

### ISSUE THREAD

**Issue by ckskr** [ckskr/capstone-project#19]

**Comment by ckskr** [comment]
# Value Proposition

**As a** user
**I want to** see when I was entering my entries
**So that** I can follow my thoughts over time 






# Acceptance Criteria

- [ ] Add local storage to the App
- [ ] Entries are still visible after refreshing the page

# Tasks

(for developers team)

- [ ] Create new branch
- [ ] import {persist} from 'zustand/middleware';
- [ ] Add persist to store 

# Complexity

M

**Comment by j-eick** [comment]
Nice 👍 

Suggestion: date() should work fine. Pretty easy to use. Let me know when you implement it.
