### ISSUE TITLE
#6 Add start page to app

### ISSUE THREAD

**Issue by ckskr** [ckskr/capstone-project#20]

**Comment by ckskr** [comment]
# Value Proposition

**As a** user
**I want to** see a starting page when entering the app 
**So that** I can decide whether I want to go to my entries or the form page




![Image](https://user-images.githubusercontent.com/102232516/187685088-a6efa674-b8b9-4e03-88ac-82080a26a270.png)





# Acceptance Criteria

- [ ] A third page is visible (only when coming new to the page)
- [ ] Two Buttons are shown 
- [ ] On click navigate to either form or entry page

# Tasks

(for developers team)

- [ ] Create new branch
- [ ] Insert new page
- [ ] Insert headlines 
- [ ] Insert clickable fields for routing
- [ ] Navigation to other pages with routing

# Complexity

M
