### ISSUE TITLE
#8 Add breathing exercise

### ISSUE THREAD

**Issue by ckskr** [ckskr/capstone-project#23]

**Comment by ckskr** [comment]
# Value Proposition

**As a** user
**I want to** take some deep breaths
**So that** I can focus on myself again



# Description


![Image](https://user-images.githubusercontent.com/102232516/187995183-cd95e757-8794-4db6-94ed-6bcead56f94c.png)



# Acceptance Criteria

- [ ] A moving circle is shown for "breath in" and "breath out"
- [ ] The nav bar has a third Link

# Tasks

(for developers team)

- [ ] Create new branch
- [ ] Add breathing page to the navigation
- [ ] Integrate a moving in and moving out circle with css

# Complexity

M

**Comment by j-eick** [comment]
> As a user
I want to take some deep breaths
So that I can focus on myself again

I know that I need to breathe, but what does that have to do with the app? Most people probably would understand, but for the sake of more clarity...

Suggestion:
As a user
I want to be guided during the breathing exercise (visually)
So that I can learn how to breathe correctly

> The nav bar has a third Link

That does what?

**Comment by PhilipZi** [comment]
> The nav bar has a third Link

I need to agree with Josh, i dont really understand the third link thing 

>  Add breathing page to the navigation

also here in the description i dont see any  breathing page to click on. 

I think if you fix this its a good userstory :)
