### ISSUE TITLE
#10 Add some testing

### ISSUE THREAD

**Issue by ckskr** [ckskr/capstone-project#26]

**Comment by ckskr** [comment]
# Value Proposition

**As a** developer
**I want to** test my breathing exercise
**So that** I can see if it works correctly 


# Acceptance Criteria

- [ ] A test tests the breath animation 

# Tasks

(for developers team)

- [ ] Create new branch
- [ ] Create a test for the breathing exercise


# Complexity

M
