### ISSUE TITLE
#11 Add storybook

### ISSUE THREAD

**Issue by ckskr** [ckskr/capstone-project#27]

**Comment by ckskr** [comment]
# Value Proposition

**As a** developer
**I want to** add my button to storybook 
**So that** I can see all varities 


# Acceptance Criteria

- [ ] Button is added to storybook 

# Tasks

(for developers team)

- [ ] Create new branch
- [ ] Create story for the button 
- [ ] Add to storybook

# Complexity

M
