### ISSUE TITLE
#1

### ISSUE THREAD

**Issue by ckskr** [ckskr/capstone-project#3]

**Comment by ckskr** [comment]
# Value Proposition

**As a** user
**I want to** insert the things that made me grateful today
**So that** I can read it afterwards in my list of entries 

# Description


![Image](https://user-images.githubusercontent.com/102232516/184364968-58daf2ac-1efc-4abc-80e8-c94a251c8987.png)


# Acceptance Criteria
- [ ] A headline with a question is shown
- [ ] An input field for the users input is shown (label: "tbd")
- [ ] A submit button is displayed
- [ ] The input field is required
- [ ] After submitting the input is displayed in the list of entries
- [ ] Another headline marks the beginning of the entry list

# Tasks

(for developers team)

- [ ] Create a form component with one required input field
- [ ] add a submit button to the form
- [ ] add event.preventDefault to the form submit
- [ ] Create form validation (required, no empty spaces)
- [ ] Render the answers to a card 

# Complexity
L

**Comment by JessicaLoers** [comment]
**Hi @ckskr**  👋
Great first User Story. 
I have just a few super picky suggestions:

 **Description**
 - the headline at the top of your wire frame "Great to have you here" is not mentioned in the user story. Only the existing elements should be visible in the wire frame, so please add the headline to your user story or remove it from the wire frame. 
 
 **Acceptance Criteria**
 - Submit button: Your button says "Add to my Diary", which is probably the list 😉. However, the Diary isn't mentioned anywhere else. I would suggest you to stay consistent and perhaps add Diary to the list headline. 
 - What happen if the user send the form without the required input field?  Is there a message shown? 
 - The "things I'm grateful" for are showing as a list, but the input is probably a `<textarea>` - I would like to recommend you to think about the implementation. 
 
 **Tasks**
 - I'm a little bit confused about: _Render the **answers** to a card_  What answers? 😬
 - You could add **Component Testing** (requested) to your tasks.
 - You could add **Story Book** (optional) to your tasks.
 
 If you have any questions, feel free to ask.

**Comment by RobertBReich** [comment]
Looks good, found a typo in AC, row 7
"to fill the input fiels" +d

cheers
R.
