### ISSUE TITLE
#2 Add "update" Button to the entries

### ISSUE THREAD

**Issue by ckskr** [ckskr/capstone-project#4]

**Comment by ckskr** [comment]
# Value Proposition

**As a** user
**I want to** have the possibility of updating my entries
**So that** I can correct spelling mistakes or add more things I am grateful for

# Description

![Image](https://user-images.githubusercontent.com/102232516/184367012-377717dc-1382-4370-9856-0fd3a7408a3f.png)

# Acceptance Criteria

- [ ] An update button is shown
- [ ] After clicking the button each entry can be updated
- [ ] Changes are saved to the card after another click on the button

# Tasks

(for developers team)

- [ ] Add Update Button to the Entry Component
- [ ] On click the entry can be updated
- [ ] On second click changes are saved to the entry
- [ ] trim whitespaces in updated entries

# Complexity

M

**Comment by tsimvris** [comment]
Hi Claudia,

A small suggestion : 

I think that the update button text should change to "save " or something , so that the user gets a visual feedback that he can save the updated information. 
Maybe something like "edit" and then "save" .

Everything else looks very nice.

Keep up 👍🏼

**Comment by ckskr** [comment]
Thanks for the review. I wanted to leave that for a later user story but I will try to implement it right now ;)
