### ISSUE TITLE
#3 Create Navbar and split content

### ISSUE THREAD

**Issue by ckskr** [ckskr/capstone-project#6]

**Comment by ckskr** [comment]
# Value Proposition

**As a** user
**I want to** have the possibility to switch between my diary entries and the form
**So that** I have it seperated

# Description

![Image]()

# Acceptance Criteria

- [ ] A nav bar is shown with two buttons 
- [ ] One can switch from Home (=form) to Diary entries
- [ ] The nav bar is shown on the bo^ttom of the page

# Tasks

(for developers team)

- [ ] 


# Complexity

M

**Comment by j-eick** [comment]
> choose to do it

The first thing that pops up in my mind is "do what?" Obviously... to save things, but I'd still specify this part a bit more. 
Rather say "Choose to use/implement Zustand or useState, to make w more accessibly (for components x, y, z).
