### ISSUE TITLE
Add "delete" button to the entries

### ISSUE THREAD

**Issue by ckskr** [ckskr/capstone-project#9]

**Comment by ckskr** [comment]
# Value Proposition

**As a** user
**I want to** have the possibility of deleting my entries
**So that** I can delete unnecessary entries

# Description


![Image](https://user-images.githubusercontent.com/102232516/186657523-dba8ec55-8d7e-4552-88f7-e56a67d1f49b.png)


# Acceptance Criteria

- [ ] A delete button is shown
- [ ] On click the entry is deleted

# Tasks

(for developers team)

- [ ] Create new branch
- [ ] Add delete Button to the Entry Component
- [ ] On click the entry is deleted


# Complexity

M

**Comment by CJAkkuec** [comment]
>Tasks
>[...]
>Add delete Button to the Entry Component
I think the (delete) Button could potentially be its own re-usable component.
>On click the entry is deleted
... deleted from where? I feel like, as a developer, I'd probably prefer my tasks to be a little more specific. Try to write your tasks without assuming any prior knowledge. Also: what do you need to do to accomplish your criteria of having the entry deleted on click? This is more interesting to the developer than repeating the criteria itself. :)

**Comment by j-eick** [comment]
If you know how you are going to implement the delete functionality, a bit more elaboration on that would be nice. 
Try to avoid writing the same things in AC and Task.

Aside from that, looks good. 🤌🏼
